if htme_globalGet("name["+string(htme_globalGet("guardSelected"))+"]") = global.name //If Night Guard
{
	//Start loading Night Guard sprites
	if htme_globalGet("mapSelected") = 0 //FNaF1
	{
		sprite_prefetch(spr_office1);
		sprite_prefetch(spr_office1_leftturn);
		sprite_prefetch(spr_office1_leftturn_closed);
		sprite_prefetch(spr_office1_rightturn);
		sprite_prefetch(spr_office1_rightturn_closed);
		sprite_prefetch(spr_office1_left);
		sprite_prefetch(spr_office1_left_door);
		sprite_prefetch(spr_office1_right);
		sprite_prefetch(spr_office1_right_door);
		sprite_prefetch(spr_monitor);
		sprite_prefetch(spr_handunit_up);
		sprite_prefetch(spr_handunit_up_dark);
		sprite_prefetch(spr_handunit);
		sprite_prefetch(spr_switch);
		sprite_prefetch(spr_cameramap1);
		sprite_prefetch(spr_cam1a);
		sprite_prefetch(spr_cam1b);
		sprite_prefetch(spr_cam1c);
		sprite_prefetch(spr_cam2a);
		sprite_prefetch(spr_cam2b);
		sprite_prefetch(spr_cam3);
		sprite_prefetch(spr_cam4a);
		sprite_prefetch(spr_cam4b);
		sprite_prefetch(spr_cam5);
		sprite_prefetch(spr_cam6);
		sprite_prefetch(spr_cam7);
		sprite_prefetch(spr_cam1a_button);
		sprite_prefetch(spr_cam1b_button);
		sprite_prefetch(spr_cam1c_button);
		sprite_prefetch(spr_cam2a_button);
		sprite_prefetch(spr_cam2b_button);
		sprite_prefetch(spr_cam3_button);
		sprite_prefetch(spr_cam4a_button);
		sprite_prefetch(spr_cam4b_button);
		sprite_prefetch(spr_cam5_button);
		sprite_prefetch(spr_cam6_button);
		sprite_prefetch(spr_cam7_button);
	}
	if htme_globalGet("mapSelected") = 1 //FNaF2
	{
		sprite_prefetch(spr_office2);
		sprite_prefetch(spr_office2_leftturn);
		sprite_prefetch(spr_office2_rightturn);
		sprite_prefetch(spr_office2_left);
		sprite_prefetch(spr_office2_right);
		sprite_prefetch(spr_monitor);
		sprite_prefetch(spr_handunit_up);
		sprite_prefetch(spr_handunit_up_dark);
		sprite_prefetch(spr_handunit);
		sprite_prefetch(spr_mask_flip);
		sprite_prefetch(spr_mask);
		sprite_prefetch(spr_switch);
		sprite_prefetch(spr_minimap2);
		sprite_prefetch(spr_cam01);
		sprite_prefetch(spr_cam02);
		sprite_prefetch(spr_cam03);
		sprite_prefetch(spr_cam04);
		sprite_prefetch(spr_cam05);
		sprite_prefetch(spr_cam06);
		sprite_prefetch(spr_cam07);
		sprite_prefetch(spr_cam08);
		sprite_prefetch(spr_cam09);
		sprite_prefetch(spr_cam10);
		sprite_prefetch(spr_cam11);
		sprite_prefetch(spr_cam12);
		sprite_prefetch(spr_cam01_button);
		sprite_prefetch(spr_cam02_button);
		sprite_prefetch(spr_cam03_button);
		sprite_prefetch(spr_cam04_button);
		sprite_prefetch(spr_cam05_button);
		sprite_prefetch(spr_cam06_button);
		sprite_prefetch(spr_cam07_button);
		sprite_prefetch(spr_cam08_button);
		sprite_prefetch(spr_cam09_button);
		sprite_prefetch(spr_cam10_button);
		sprite_prefetch(spr_cam11_button);
		sprite_prefetch(spr_cam12_button);
		sprite_prefetch(spr_office2_animatronics);
	}
}
else //If Animatronic
{
	//Start loading Animatronic sprites
	if htme_globalGet("mapSelected") = 0 //FNaF1
	{
		sprite_prefetch(spr_icons);
		sprite_prefetch(spr_minimap1);
		sprite_prefetch(spr_minimap1_puppet);
		sprite_prefetch(spr_minimap1_disabled);
		sprite_prefetch(spr_minimap1_springtrap);
		sprite_prefetch(spr_minimap1_saferoom);
		sprite_prefetch(spr_freddy_d);
		sprite_prefetch(spr_freddy_d_special);
		sprite_prefetch(spr_freddy_l);
		sprite_prefetch(spr_freddy_r);
		sprite_prefetch(spr_freddy_u);
		sprite_prefetch(spr_bonnie_d);
		sprite_prefetch(spr_bonnie_l);
		sprite_prefetch(spr_bonnie_r);
		sprite_prefetch(spr_bonnie_u);
		sprite_prefetch(spr_chica_d);
		sprite_prefetch(spr_chica_l);
		sprite_prefetch(spr_chica_r);
		sprite_prefetch(spr_chica_u);
		sprite_prefetch(spr_foxy_d);
		sprite_prefetch(spr_foxy_l);
		sprite_prefetch(spr_foxy_r);
		sprite_prefetch(spr_foxy_u);
		sprite_prefetch(spr_puppet_d);
		sprite_prefetch(spr_puppet_d_special);
		sprite_prefetch(spr_puppet_l);
		sprite_prefetch(spr_puppet_r);
		sprite_prefetch(spr_puppet_u);
		sprite_prefetch(spr_springtrap_d);
		sprite_prefetch(spr_springtrap_l);
		sprite_prefetch(spr_springtrap_r);
		sprite_prefetch(spr_springtrap_u);
		sprite_prefetch(spr_mimic_d);
		sprite_prefetch(spr_mimic_l);
		sprite_prefetch(spr_mimic_r);
		sprite_prefetch(spr_mimic_u);
		sprite_prefetch(spr_table1);
		sprite_prefetch(spr_arcades1);
		sprite_prefetch(spr_tv1);
		sprite_prefetch(spr_tv2);
		sprite_prefetch(spr_shelf);
		sprite_prefetch(spr_backstage1_shelves);
		sprite_prefetch(spr_backstage1_table);
		sprite_prefetch(spr_cove1_curtain);
		sprite_prefetch(spr_cove1_stage);
		sprite_prefetch(spr_door_left1);
		sprite_prefetch(spr_door_right1);
	}
	if htme_globalGet("mapSelected") = 1 //FNaF2
	{
		sprite_prefetch(spr_icons);
		sprite_prefetch(spr_minimap2);
		sprite_prefetch(spr_minimap2_puppet);
		sprite_prefetch(spr_minimap2_disabled);
		sprite_prefetch(spr_minimap2_springtrap);
		sprite_prefetch(spr_tfreddy_d);
		sprite_prefetch(spr_tfreddy_d_special);
		sprite_prefetch(spr_tfreddy_l);
		sprite_prefetch(spr_tfreddy_r);
		sprite_prefetch(spr_tfreddy_u);
		sprite_prefetch(spr_tbonnie_d);
		sprite_prefetch(spr_tbonnie_l);
		sprite_prefetch(spr_tbonnie_r);
		sprite_prefetch(spr_tbonnie_u);
		sprite_prefetch(spr_tchica_d);
		sprite_prefetch(spr_tchica_l);
		sprite_prefetch(spr_tchica_r);
		sprite_prefetch(spr_tchica_u);
		sprite_prefetch(spr_mangle_d);
		sprite_prefetch(spr_mangle_l);
		sprite_prefetch(spr_mangle_r);
		sprite_prefetch(spr_mangle_u);
		sprite_prefetch(spr_wfreddy_d);
		sprite_prefetch(spr_wfreddy_d_special);
		sprite_prefetch(spr_wfreddy_l);
		sprite_prefetch(spr_wfreddy_r);
		sprite_prefetch(spr_wfreddy_u);
		sprite_prefetch(spr_wbonnie_d);
		sprite_prefetch(spr_wbonnie_l);
		sprite_prefetch(spr_wbonnie_r);
		sprite_prefetch(spr_wbonnie_u);
		sprite_prefetch(spr_wchica_d);
		sprite_prefetch(spr_wchica_l);
		sprite_prefetch(spr_wchica_r);
		sprite_prefetch(spr_wchica_u);
		sprite_prefetch(spr_wfoxy_d);
		sprite_prefetch(spr_wfoxy_l);
		sprite_prefetch(spr_wfoxy_r);
		sprite_prefetch(spr_wfoxy_u);
		sprite_prefetch(spr_puppet_d);
		sprite_prefetch(spr_puppet_d_special);
		sprite_prefetch(spr_puppet_l);
		sprite_prefetch(spr_puppet_r);
		sprite_prefetch(spr_puppet_u);
		sprite_prefetch(spr_springtrap_d);
		sprite_prefetch(spr_springtrap_l);
		sprite_prefetch(spr_springtrap_r);
		sprite_prefetch(spr_springtrap_u);
		sprite_prefetch(spr_mimic_d);
		sprite_prefetch(spr_mimic_l);
		sprite_prefetch(spr_mimic_r);
		sprite_prefetch(spr_mimic_u);
		sprite_prefetch(spr_table2);
		sprite_prefetch(spr_table2_side);
		sprite_prefetch(spr_balloons);
		sprite_prefetch(spr_presents);
		sprite_prefetch(spr_vent);
	}
}

room_goto_next();