if htme_globalGet("mapSelected") = 0 //FNaF1
{
	//Load the Chosen Animatronics
	if htme_globalGet("freddyTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_freddy);
		sprite_prefetch(spr_stage_freddy);
		sprite_prefetch(spr_dining_freddy);
		sprite_prefetch(spr_bathroom_freddy);
		sprite_prefetch(spr_lefthall_freddy);
		sprite_prefetch(spr_righthall_freddy);
	}
	if htme_globalGet("bonnieTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_bonnie);
		sprite_prefetch(spr_stage_bonnie);
		sprite_prefetch(spr_dining_bonnie);
		sprite_prefetch(spr_bathroom_bonnie);
		sprite_prefetch(spr_lefthall_bonnie);
		sprite_prefetch(spr_righthall_bonnie);
	}
	if htme_globalGet("chicaTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_chica);
		sprite_prefetch(spr_stage_chica);
		sprite_prefetch(spr_dining_chica);
		sprite_prefetch(spr_bathroom_chica);
		sprite_prefetch(spr_lefthall_chica);
		sprite_prefetch(spr_righthall_chica);
	}
	if htme_globalGet("foxyTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_foxy);
		sprite_prefetch(spr_dining_foxy);
		sprite_prefetch(spr_bathroom_foxy);
		sprite_prefetch(spr_lefthall_foxy);
		sprite_prefetch(spr_righthall_foxy);
	}
	if htme_globalGet("puppetTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_puppet);
		sprite_prefetch(spr_puppetflicker);
		sprite_prefetch(spr_puppetblock);
	}
	if htme_globalGet("springtrapTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_springtrap);
		sprite_prefetch(spr_stage_springtrap);
		sprite_prefetch(spr_dining_springtrap);
		sprite_prefetch(spr_bathroom_springtrap);
		sprite_prefetch(spr_lefthall_springtrap);
		sprite_prefetch(spr_righthall_springtrap);
	}
	if htme_globalGet("mimicTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_mimic);
		sprite_prefetch(spr_stage_mimic);
		sprite_prefetch(spr_dining_mimic);
		sprite_prefetch(spr_bathroom_mimic);
		sprite_prefetch(spr_lefthall_mimic);
		sprite_prefetch(spr_righthall_mimic);
	}
	
	room_goto(rm_office1);
}
if htme_globalGet("mapSelected") = 1 //FNaF2
{
	//Load the Chosen Animatronics
	if htme_globalGet("tfreddyTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_tfreddy);
		sprite_prefetch(spr_stage_tfreddy);
		sprite_prefetch(spr_game_tfreddy);
		sprite_prefetch(spr_prize_tfreddy);
		sprite_prefetch(spr_cove2_tfreddy);
		sprite_prefetch(spr_hall_tfreddy);
		sprite_prefetch(spr_partsandservice_tfreddy);
		sprite_prefetch(spr_party1_tfreddy);
		sprite_prefetch(spr_party2_tfreddy);
		sprite_prefetch(spr_party3_tfreddy);
		sprite_prefetch(spr_party4_tfreddy);
		sprite_prefetch(spr_stage_tfreddy_light);
		sprite_prefetch(spr_game_tfreddy_light);
		sprite_prefetch(spr_prize_tfreddy_light);
		sprite_prefetch(spr_cove2_tfreddy_light);
		sprite_prefetch(spr_hall_tfreddy_light);
		sprite_prefetch(spr_partsandservice_tfreddy_light);
		sprite_prefetch(spr_party1_tfreddy_light);
		sprite_prefetch(spr_party3_tfreddy_light);
		sprite_prefetch(spr_party4_tfreddy_light);
	}
	if htme_globalGet("tbonnieTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_tbonnie);
		sprite_prefetch(spr_stage_tbonnie);
		sprite_prefetch(spr_game_tbonnie);
		sprite_prefetch(spr_prize_tbonnie);
		sprite_prefetch(spr_cove2_tbonnie);
		sprite_prefetch(spr_hall_tbonnie);
		sprite_prefetch(spr_partsandservice_tbonnie);
		sprite_prefetch(spr_party1_tbonnie);
		sprite_prefetch(spr_party2_tbonnie);
		sprite_prefetch(spr_party3_tbonnie);
		sprite_prefetch(spr_party4_tbonnie);
		sprite_prefetch(spr_stage_tbonnie_light);
		sprite_prefetch(spr_game_tbonnie_light);
		sprite_prefetch(spr_prize_tbonnie_light);
		sprite_prefetch(spr_cove2_tbonnie_light);
		sprite_prefetch(spr_hall_tbonnie_light);
		sprite_prefetch(spr_partsandservice_tbonnie_light);
		sprite_prefetch(spr_party1_tbonnie_light);
		sprite_prefetch(spr_party3_tbonnie_light);
	}
	if htme_globalGet("tchicaTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_tchica);
		sprite_prefetch(spr_stage_tchica);
		sprite_prefetch(spr_game_tchica);
		sprite_prefetch(spr_prize_tchica);
		sprite_prefetch(spr_cove2_tchica);
		sprite_prefetch(spr_hall_tchica);
		sprite_prefetch(spr_partsandservice_tchica);
		sprite_prefetch(spr_party1_tchica);
		sprite_prefetch(spr_party2_tchica);
		sprite_prefetch(spr_party3_tchica);
		sprite_prefetch(spr_party4_tchica);
		sprite_prefetch(spr_stage_tchica_light);
		sprite_prefetch(spr_game_tchica_light);
		sprite_prefetch(spr_prize_tchica_light);
		sprite_prefetch(spr_cove2_tchica_light);
		sprite_prefetch(spr_hall_tchica_light);
		sprite_prefetch(spr_partsandservice_tchica_light);
		sprite_prefetch(spr_party2_tchica_light);
		sprite_prefetch(spr_party3_tchica_light);
	}
	if htme_globalGet("mangleTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_mangle);
		sprite_prefetch(spr_game_mangle);
		sprite_prefetch(spr_prize_mangle);
		sprite_prefetch(spr_cove2_mangle);
		sprite_prefetch(spr_hall_mangle);
		sprite_prefetch(spr_partsandservice_mangle);
		sprite_prefetch(spr_party1_mangle);
		sprite_prefetch(spr_party2_mangle);
		sprite_prefetch(spr_party3_mangle);
		sprite_prefetch(spr_party4_mangle);
		sprite_prefetch(spr_game_mangle_light);
		sprite_prefetch(spr_prize_mangle_light);
		sprite_prefetch(spr_cove2_mangle_light);
		sprite_prefetch(spr_hall_mangle_light);
		sprite_prefetch(spr_partsandservice_mangle_light);
		sprite_prefetch(spr_party1_mangle_light);
		sprite_prefetch(spr_party2_mangle_light);
		sprite_prefetch(spr_party3_mangle_light);
		sprite_prefetch(spr_party4_mangle_light);
		sprite_prefetch(spr_foxy_head);
		sprite_prefetch(spr_foxy_arm);
		sprite_prefetch(spr_foxy_left);
		sprite_prefetch(spr_foxy_right);
	}
	if htme_globalGet("wfreddyTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_wfreddy);
		sprite_prefetch(spr_stage_wfreddy);
		sprite_prefetch(spr_game_wfreddy);
		sprite_prefetch(spr_prize_wfreddy);
		sprite_prefetch(spr_cove2_wfreddy);
		sprite_prefetch(spr_hall_wfreddy);
		sprite_prefetch(spr_partsandservice_wfreddy);
		sprite_prefetch(spr_party1_wfreddy);
		sprite_prefetch(spr_party2_wfreddy);
		sprite_prefetch(spr_party3_wfreddy);
		sprite_prefetch(spr_party4_wfreddy);
		sprite_prefetch(spr_stage_wfreddy_light);
		sprite_prefetch(spr_game_wfreddy_light);
		sprite_prefetch(spr_prize_wfreddy_light);
		sprite_prefetch(spr_cove2_wfreddy_light);
		sprite_prefetch(spr_hall_wfreddy_light);
		sprite_prefetch(spr_partsandservice_wfreddy_light);
		sprite_prefetch(spr_party1_wfreddy_light);
		sprite_prefetch(spr_party3_wfreddy_light);
		sprite_prefetch(spr_party4_wfreddy_light);
	}
	if htme_globalGet("wbonnieTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_wbonnie);
		sprite_prefetch(spr_stage_wbonnie);
		sprite_prefetch(spr_game_wbonnie);
		sprite_prefetch(spr_prize_wbonnie);
		sprite_prefetch(spr_cove2_wbonnie);
		sprite_prefetch(spr_hall_wbonnie);
		sprite_prefetch(spr_partsandservice_wbonnie);
		sprite_prefetch(spr_party1_wbonnie);
		sprite_prefetch(spr_party2_wbonnie);
		sprite_prefetch(spr_party3_wbonnie);
		sprite_prefetch(spr_party4_wbonnie);
		sprite_prefetch(spr_stage_wbonnie_light);
		sprite_prefetch(spr_game_wbonnie_light);
		sprite_prefetch(spr_prize_wbonnie_light);
		sprite_prefetch(spr_cove2_wbonnie_light);
		sprite_prefetch(spr_hall_wbonnie_light);
		sprite_prefetch(spr_partsandservice_wbonnie_light);
		sprite_prefetch(spr_party1_wbonnie_light);
		sprite_prefetch(spr_party3_wbonnie_light);
	}
	if htme_globalGet("wchicaTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_wchica);
		sprite_prefetch(spr_stage_wchica);
		sprite_prefetch(spr_game_wchica);
		sprite_prefetch(spr_prize_wchica);
		sprite_prefetch(spr_cove2_wchica);
		sprite_prefetch(spr_hall_wchica);
		sprite_prefetch(spr_partsandservice_wchica);
		sprite_prefetch(spr_party1_wchica);
		sprite_prefetch(spr_party2_wchica);
		sprite_prefetch(spr_party3_wchica);
		sprite_prefetch(spr_party4_wchica);
		sprite_prefetch(spr_stage_wchica_light);
		sprite_prefetch(spr_game_wchica_light);
		sprite_prefetch(spr_prize_wchica_light);
		sprite_prefetch(spr_cove2_wchica_light);
		sprite_prefetch(spr_hall_wchica_light);
		sprite_prefetch(spr_partsandservice_wchica_light);
		sprite_prefetch(spr_party2_wchica_light);
		sprite_prefetch(spr_party3_wchica_light);
	}
	if htme_globalGet("wfoxyTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_wfoxy);
		sprite_prefetch(spr_game_wfoxy);
		sprite_prefetch(spr_prize_wfoxy);
		sprite_prefetch(spr_cove2_wfoxy);
		sprite_prefetch(spr_hall_wfoxy);
		sprite_prefetch(spr_partsandservice_wfoxy);
		sprite_prefetch(spr_party1_wfoxy);
		sprite_prefetch(spr_party2_wfoxy);
		sprite_prefetch(spr_party3_wfoxy);
		sprite_prefetch(spr_party4_wfoxy);
		sprite_prefetch(spr_game_wfoxy_light);
		sprite_prefetch(spr_prize_wfoxy_light);
		sprite_prefetch(spr_cove2_wfoxy_light);
		sprite_prefetch(spr_hall_wfoxy_light);
		sprite_prefetch(spr_partsandservice_wfoxy_light);
		sprite_prefetch(spr_party1_wfoxy_light);
		sprite_prefetch(spr_party2_wfoxy_light);
		sprite_prefetch(spr_party3_wfoxy_light);
		sprite_prefetch(spr_party4_wfoxy_light);
		sprite_prefetch(spr_foxy_head);
		sprite_prefetch(spr_foxy_arm);
		sprite_prefetch(spr_foxy_left);
		sprite_prefetch(spr_foxy_right);
	}
	if htme_globalGet("puppetTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_puppet);
		sprite_prefetch(spr_puppetflicker);
		sprite_prefetch(spr_puppetblock);
	}
	if htme_globalGet("springtrapTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_springtrap);
		sprite_prefetch(spr_stage_springtrap);
		sprite_prefetch(spr_game_springtrap);
		sprite_prefetch(spr_prize_springtrap);
		sprite_prefetch(spr_cove2_springtrap);
		sprite_prefetch(spr_hall_springtrap);
		sprite_prefetch(spr_partsandservice_springtrap);
		sprite_prefetch(spr_party1_springtrap);
		sprite_prefetch(spr_party2_springtrap);
		sprite_prefetch(spr_party3_springtrap);
		sprite_prefetch(spr_party4_springtrap);
		sprite_prefetch(spr_hall_springtrap_light);
		sprite_prefetch(spr_partsandservice_springtrap_light);
	}
	if htme_globalGet("mimicTaken") != "none"
	{
		sprite_prefetch(spr_jumpscare_mimic);
		sprite_prefetch(spr_stage_mimic2);
		sprite_prefetch(spr_game_mimic);
		sprite_prefetch(spr_prize_mimic);
		sprite_prefetch(spr_cove2_mimic);
		sprite_prefetch(spr_hall_mimic);
		sprite_prefetch(spr_partsandservice_mimic);
		sprite_prefetch(spr_party1_mimic);
		sprite_prefetch(spr_party2_mimic);
		sprite_prefetch(spr_party3_mimic);
		sprite_prefetch(spr_party4_mimic);
		sprite_prefetch(spr_stage_mimic2_light);
		sprite_prefetch(spr_game_mimic_light);
		sprite_prefetch(spr_prize_mimic_light);
		sprite_prefetch(spr_cove2_mimic_light);
		sprite_prefetch(spr_hall_mimic_light);
		sprite_prefetch(spr_partsandservice_mimic_light);
		sprite_prefetch(spr_party1_mimic_light);
		sprite_prefetch(spr_party2_mimic_light);
		sprite_prefetch(spr_party3_mimic_light);
		sprite_prefetch(spr_party4_mimic_light);
		sprite_prefetch(spr_foxy_head);
		sprite_prefetch(spr_foxy_arm);
		sprite_prefetch(spr_foxy_left);
		sprite_prefetch(spr_foxy_right);
	}
	
	room_goto(rm_office2);
}